## Data Challenge: RealCrowd risk of loss model

    1. Goals:
        a) Synthesize and clean the CMBS data files into one usable database
        b) Find a high correlating economic factor, e.g. cost of living, demographics, housing affordability, employment numbers, or other factors (Market inputs that could have an impact or predictor for real estate values)
        
    2. Deliverables:
        a) Written summary of results
        b) Code as repo on github
        c) Summary of challenges
        d) Is making a risk model feasible?
    
    3. Observations of data analysis:
        a)

    4. Conclusions:
        a)

In [1]:
import pandas as pd

In [33]:
# Function for reading xlsx files

def makeDf(filepathway, sheet):

    '''Given a filepathway and sheet of an xlsx file, load that file's sheet into a dataframe'''
    
    xlsx = pd.ExcelFile(filepathway)
    dataframe = pd.read_excel(xlsx, sheet)
    
    return dataframe

In [34]:
file = '/Users/donalddressen/Desktop/realcrowd_dc/Annex A Data/Annex A Upload 4-16-15/CGCMT 2015-GC27 Annex A.xlsx'
sheet = 'Annex'

df = makeDf(file, sheet)

In [35]:
df.head()

,CGCMT 2015-GC27 Annex A,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Unnamed: 153
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Control Number,Loan / Property Flag,Footnotes,Mortgage Loan Seller,Originator,Property Name,Related Group,Crossed Group,Address,City,...,Cash Management Triggers,Ground Lease Y/N,Ground Lease Expiration Date,Annual Ground Lease Payment ($),Cut-off Date B Note Balance ($),B Note Interest Rate,Cut-off Date Mezzanine Debt Balance ($),Mezzanine Debt Interest Rate,Terrorism Insurance Required,Control Number
4,1,Loan,"8, 9, 10",GSMC,GSMC,Kemper Lakes Business Center,NAP,NAP,"1, 2, 3, 4 Corporate Drive",Long Grove,...,"(i) the occurrence of an Event of Default, (ii...",No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1

## Data Challenge: RealCrowd risk of loss model

    1. Goals:
        a) Synthesize and clean the CMBS data files into one usable database
        b) Find a high correlating economic factor, e.g. cost of living, demographics, housing affordability, employment numbers, or other factors (Market inputs that could have an impact or predictor for real estate values)
        
    2. Deliverables:
        a) Written summary of results
        b) Code as repo on github
        c) Summary of challenges
        d) Is making a risk model feasible?
    
    3. Observations of data analysis:
        a)

    4. Conclusions:
        a)